# Generated by Django 6.0.6 on 2026-06-27 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReadme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(max_length=500)),
                ('owner', models.CharField(max_length=255)),
                ('repo', models.CharField(max_length=255)),
                ('branch', models.CharField(default='main', max_length=100)),
                ('readme_content', models.TextField()),
                ('tone', models.CharField(default='technical', max_length=50)),
                ('files_analyzed', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readmes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
